name: Run Deal Sniper Bot

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual triggers

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install chromium
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libdbus-1-3 libatspi2.0-0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libasound2t64
    
    - name: Install Playwright browser
      run: |
        pip install playwright
        playwright install chromium
    
    - name: Install Ollama and model
      run: |
        curl -fsSL https://ollama.ai/install.sh | sh
        sleep 5
        ollama pull mistral:7b
        ollama list
    
    - name: Create screenshots directory
      run: mkdir -p screenshots
    
    - name: Run the bot
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        echo "🚀 Starting Deal Sniper Bot..."
        python main.py
        echo "✅ Bot run completed!"
    
    - name: Upload screenshots as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: detection-screenshots
        path: screenshots/
        if-no-files-found: ignore
    
    - name: Upload logs as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bot-logs
        path: scraper.log
        if-no-files-found: ignore
